CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS INGREDIENTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(255),
    Price DOUBLE PRECISION,
    Quantity DOUBLE PRECISION,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(255) NOT NULL,
    Phone_code VARCHAR(255),
    Phone_number VARCHAR(255),
    Is_open BOOLEAN,
    manuallyClosed BOOLEAN DEFAULT false NOT NULL,
    Status VARCHAR(255),
    Tables INTEGER DEFAULT 0,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Location_Ingredients (
    Location_id BIGINT NOT NULL,
    Ingredient_id BIGINT NOT NULL,
    Quantity DOUBLE PRECISION,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    PRIMARY KEY (Location_id, Ingredient_id),
    CONSTRAINT fk_li_location FOREIGN KEY (Location_id) REFERENCES LOCATIONS(id),
    CONSTRAINT fk_li_ingredient FOREIGN KEY (Ingredient_id) REFERENCES INGREDIENTS(id)
);

CREATE TABLE IF NOT EXISTS MENU (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Price DOUBLE PRECISION,
    Description VARCHAR(255),
    Image VARCHAR(255),
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(255),
    category_id BIGINT NOT NULL,
    Image VARCHAR(255),
    Available BOOLEAN DEFAULT true,
    Size VARCHAR(255),
    Quantity INTEGER,
    Weight DOUBLE PRECISION,
    Liters DOUBLE PRECISION,
    IsSpicy BOOLEAN,
    Flavor VARCHAR(255),
    Temperature VARCHAR(255),
    IsCarbonated BOOLEAN,
    Calories INTEGER,
    IsVegetarian BOOLEAN,
    IsVegan BOOLEAN,
    IsGlutenFree BOOLEAN,
    Additions DOUBLE PRECISION,
    Price DOUBLE PRECISION,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    CONSTRAINT fk_p_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS Menu_Products (
    Menu_id BIGINT NOT NULL,
    Product_id BIGINT NOT NULL,
    Quantity INTEGER,
    Obligatory BOOLEAN,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    PRIMARY KEY (Menu_id, Product_id),
    CONSTRAINT fk_mp_menu FOREIGN KEY (Menu_id) REFERENCES MENU(id),
    CONSTRAINT fk_mp_product FOREIGN KEY (Product_id) REFERENCES PRODUCTS(id)
);

CREATE TABLE IF NOT EXISTS Product_Ingredients (
    Product_id BIGINT NOT NULL,
    Ingredient_id BIGINT NOT NULL,
    PRIMARY KEY (Product_id, Ingredient_id),
    CONSTRAINT fk_pi_product FOREIGN KEY (Product_id) REFERENCES PRODUCTS(id),
    CONSTRAINT fk_pi_ingredient FOREIGN KEY (Ingredient_id) REFERENCES INGREDIENTS(id)
);

CREATE TABLE IF NOT EXISTS OFFER (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description VARCHAR(255),
    Image VARCHAR(255),
    Price DOUBLE PRECISION,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Offer_Products (
    Offer_id BIGINT NOT NULL,
    Product_id BIGINT NOT NULL,
    Quantity INTEGER,
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    PRIMARY KEY (Offer_id, Product_id),
    CONSTRAINT fk_op_offer FOREIGN KEY (Offer_id) REFERENCES OFFER(id),
    CONSTRAINT fk_op_product FOREIGN KEY (Product_id) REFERENCES PRODUCTS(id)
);

CREATE TABLE IF NOT EXISTS Offer_Menu (
    Offer_id BIGINT NOT NULL,
    Menu_id BIGINT NOT NULL,
    PRIMARY KEY (Offer_id, Menu_id),
    CONSTRAINT fk_om_offer FOREIGN KEY (Offer_id) REFERENCES OFFER(id),
    CONSTRAINT fk_om_menu FOREIGN KEY (Menu_id) REFERENCES MENU(id)
);

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Surname VARCHAR(50) NOT NULL,
    Birthday DATE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Gender VARCHAR(255),
    Phone VARCHAR(10) NOT NULL,
    role VARCHAR(255) DEFAULT 'USER',
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    Location_id BIGINT,
    CONSTRAINT fk_u_location FOREIGN KEY (Location_id) REFERENCES LOCATIONS(id)
);

CREATE TABLE IF NOT EXISTS UserFavoriteMenu (
    user_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    PRIMARY KEY (user_id, menu_id),
    CONSTRAINT fk_ufm_user FOREIGN KEY (user_id) REFERENCES USERS(id),
    CONSTRAINT fk_ufm_menu FOREIGN KEY (menu_id) REFERENCES MENU(id)
);

CREATE TABLE IF NOT EXISTS UserFavoriteProduct (
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_ufp_user FOREIGN KEY (user_id) REFERENCES USERS(id),
    CONSTRAINT fk_ufp_product FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Order_id VARCHAR(255) NOT NULL,
    Code VARCHAR(255),
    Service_type VARCHAR(255) NOT NULL,
    Order_type VARCHAR(255),
    Table_number VARCHAR(255),
    Payment_type VARCHAR(255),
    Payment_amount DECIMAL(38,2),
    Total_at DECIMAL(38,2),
    Status VARCHAR(255),
    Created_at TIMESTAMP NOT NULL,
    Updated_at TIMESTAMP NOT NULL,
    User_id BIGINT,
    Location_id BIGINT,
    CONSTRAINT fk_o_user FOREIGN KEY (User_id) REFERENCES USERS(id),
    CONSTRAINT fk_o_location FOREIGN KEY (Location_id) REFERENCES LOCATIONS(id)
);

CREATE TABLE IF NOT EXISTS Order_Products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Order_id BIGINT,
    Product_id BIGINT,
    Offer_id BIGINT,
    Menu_id BIGINT,
    Additions DECIMAL(38,2),
    Quantity INTEGER,
    Price DECIMAL(38,2),
    Special_note VARCHAR(255),
    createdAt TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    CONSTRAINT fk_op_order FOREIGN KEY (Order_id) REFERENCES ORDERS(id),
    CONSTRAINT fk_op_product_ref FOREIGN KEY (Product_id) REFERENCES PRODUCTS(id),
    CONSTRAINT fk_op_offer_ref FOREIGN KEY (Offer_id) REFERENCES OFFER(id),
    CONSTRAINT fk_op_menu_ref FOREIGN KEY (Menu_id) REFERENCES MENU(id)
);

CREATE TABLE IF NOT EXISTS Order_Product_Ingredients (
    order_product_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    PRIMARY KEY (order_product_id, ingredient_id),
    CONSTRAINT fk_opi_order_product FOREIGN KEY (order_product_id) REFERENCES Order_Products(id),
    CONSTRAINT fk_opi_ingredient FOREIGN KEY (ingredient_id) REFERENCES INGREDIENTS(id)
);
